export interface BookTheme {
  id: string;
  name: string;
  mood: string;
  background: string;
  accent: string;
  text: string;
  font: "serif" | "sans-serif";
  border: string;
  photo_radius: string;
  ornament: string;
  /** Fond photo pleine page pour la couverture/quatrième de couverture (chemin public, ex. "/book-covers/x.jpg"). Absent pour les thèmes CSS purs. */
  cover_image?: string;
}

// Miroir exact du catalogue backend (app/Support/BookThemes.php) — les deux
// DOIVENT rester synchronisés puisque le même thème doit rendre à l'identique
// dans l'aperçu web et dans le PDF généré côté serveur.
export const BOOK_THEMES: BookTheme[] = [
  {
    id: "classic_ivory",
    name: "Classique Ivoire",
    mood: "Sobre et intemporel",
    background: "#FDF8F3",
    accent: "#712B13",
    text: "#3A2A22",
    font: "serif",
    border: "2px solid #712B13",
    photo_radius: "8px",
    ornament: "❦",
  },
  {
    id: "terre_afrique",
    name: "Terre d'Afrique",
    mood: "Chaleureux et affirmé",
    background: "#B5651D",
    accent: "#E8B84B",
    text: "#2E1E10",
    font: "sans-serif",
    border: "6px solid #4E3524",
    photo_radius: "4px",
    ornament: "✺",
  },
  {
    id: "douceur_pastel",
    name: "Douceur Pastel",
    mood: "Doux, idéal bébé/enfant",
    background: "#FBEFF5",
    accent: "#C98CA6",
    text: "#4A2F3B",
    font: "sans-serif",
    border: "3px dotted #C98CA6",
    photo_radius: "16px",
    ornament: "✿",
  },
  {
    id: "noir_or",
    name: "Noir & Or",
    mood: "Premium, soirée / anniversaire",
    background: "#111111",
    accent: "#D4AF37",
    text: "#F3E3B3",
    font: "serif",
    border: "2px double #D4AF37",
    photo_radius: "4px",
    ornament: "✦",
  },
  {
    id: "bleu_marine",
    name: "Bleu Marine",
    mood: "Moderne et épuré",
    background: "#13294B",
    accent: "#9FB8D9",
    text: "#F5F5F0",
    font: "sans-serif",
    border: "1px solid #9FB8D9",
    photo_radius: "6px",
    ornament: "✧",
  },
  {
    id: "vert_olive",
    name: "Vert Olive Nature",
    mood: "Naturel et apaisant",
    background: "#EFEFE0",
    accent: "#5B6B3E",
    text: "#33361F",
    font: "serif",
    border: "3px double #5B6B3E",
    photo_radius: "6px",
    ornament: "❧",
  },
  {
    id: "blanc_minimal",
    name: "Blanc Minimal",
    mood: "Minimaliste, scandinave",
    background: "#FFFFFF",
    accent: "#111111",
    text: "#111111",
    font: "sans-serif",
    border: "1px solid #111111",
    photo_radius: "0px",
    ornament: "",
  },
  {
    id: "kraft_scrapbook",
    name: "Kraft Scrapbook",
    mood: "Album souvenir, décontracté",
    background: "#C8A165",
    accent: "#5A3E20",
    text: "#3A2A14",
    font: "serif",
    border: "10px solid #FFFFFF",
    photo_radius: "2px",
    ornament: "❉",
  },
  {
    id: "corail_vif",
    name: "Corail Vif",
    mood: "Énergique, famille nombreuse",
    background: "#FF6B4A",
    accent: "#FFD166",
    text: "#FFFFFF",
    font: "sans-serif",
    border: "6px solid #FFD166",
    photo_radius: "12px",
    ornament: "❊",
  },
  {
    id: "bordeaux_elegant",
    name: "Bordeaux Élégant",
    mood: "Formel et élégant",
    background: "#F7F0EC",
    accent: "#6E1423",
    text: "#2B1210",
    font: "serif",
    border: "2px double #6E1423",
    photo_radius: "4px",
    ornament: "❖",
  },
  {
    id: "emeraude_royal",
    name: "Émeraude Royal",
    mood: "Prestige, réception",
    background: "#0B3D2E",
    accent: "#C9A227",
    text: "#F1E9C9",
    font: "serif",
    border: "3px double #C9A227",
    photo_radius: "6px",
    ornament: "⚜",
  },
  {
    id: "rose_vintage",
    name: "Rose Vintage",
    mood: "Romantique, mariage / couple",
    background: "#F3E1E4",
    accent: "#8C4B5B",
    text: "#3B2226",
    font: "serif",
    border: "2px solid #8C4B5B",
    photo_radius: "10px",
    ornament: "❁",
  },
  {
    id: "graphite_argent",
    name: "Graphite Argent",
    mood: "Contemporain, professionnel",
    background: "#2B2E33",
    accent: "#C7CDD3",
    text: "#ECEFF2",
    font: "sans-serif",
    border: "1px solid #C7CDD3",
    photo_radius: "4px",
    ornament: "✵",
  },
  {
    id: "sepia_ancien",
    name: "Sépia Ancien",
    mood: "Album de famille rétro",
    background: "#E4D2B0",
    accent: "#6B4226",
    text: "#402A18",
    font: "serif",
    border: "8px ridge #6B4226",
    photo_radius: "2px",
    ornament: "☙",
  },
  {
    id: "lavande_douce",
    name: "Lavande Douce",
    mood: "Élégant et apaisant",
    background: "#EDE7F6",
    accent: "#6A4C93",
    text: "#2E1F45",
    font: "serif",
    border: "2px double #6A4C93",
    photo_radius: "8px",
    ornament: "✤",
  },
  {
    id: "lune_sur_arbre",
    name: "Lune sur l'Arbre",
    mood: "Onirique, nocturne",
    background: "#EEF0EF",
    accent: "#30A67A",
    text: "#1B2C25",
    font: "serif",
    border: "2px solid #30A67A",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/tree-moon-nocturne.jpg",
  },
  {
    id: "cascade_automne",
    name: "Cascade d'Automne",
    mood: "Poétique et vivant",
    background: "#EEF0F0",
    accent: "#30A68F",
    text: "#1A2C29",
    font: "serif",
    border: "2px solid #30A68F",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/waterfall-automne.jpg",
  },
  {
    id: "feuilles_galets",
    name: "Feuilles & Galets",
    mood: "Zen, apaisant",
    background: "#EDF1F1",
    accent: "#3096A6",
    text: "#162D31",
    font: "sans-serif",
    border: "2px solid #3096A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/feuilles-galets.jpg",
  },
  {
    id: "mains_coeur",
    name: "Mains en Cœur",
    mood: "Tendre, complicité familiale",
    background: "#F0F1ED",
    accent: "#80A630",
    text: "#283017",
    font: "sans-serif",
    border: "2px solid #80A630",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/mains-coeur-vallee.jpg",
  },
  {
    id: "colombe_collines",
    name: "Colombe des Collines",
    mood: "Paix et liberté",
    background: "#EEF1EE",
    accent: "#3CA630",
    text: "#1A2F18",
    font: "sans-serif",
    border: "2px solid #3CA630",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/colombe-collines.jpg",
  },
  {
    id: "alpes_suisses",
    name: "Alpes Suisses",
    mood: "Racines suisses, grand air",
    background: "#EDF0F1",
    accent: "#3091A6",
    text: "#162C30",
    font: "sans-serif",
    border: "2px solid #3091A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/alpes-suisses.jpg",
  },
  {
    id: "chalet_alpin",
    name: "Chalet Alpin",
    mood: "Chaleureux, montagne",
    background: "#EDF1F2",
    accent: "#308EA6",
    text: "#142C32",
    font: "serif",
    border: "2px solid #308EA6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/chalet-alpin.jpg",
  },
  {
    id: "racines_afrique",
    name: "Racines d'Afrique",
    mood: "Fier héritage africain",
    background: "#F5EFEA",
    accent: "#AE6927",
    text: "#39230E",
    font: "serif",
    border: "2px solid #AE6927",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/racines-afrique.jpg",
  },
  {
    id: "lanternes_branche",
    name: "Lanternes du Soir",
    mood: "Cocon, veillée en famille",
    background: "#F3F1EC",
    accent: "#A68930",
    text: "#372D10",
    font: "serif",
    border: "2px solid #A68930",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/lanternes-branche.jpg",
  },
  {
    id: "cadre_fleurs_dorees",
    name: "Fleurs Dorées",
    mood: "Raffiné, floral",
    background: "#F0EFEF",
    accent: "#A65C30",
    text: "#2B211B",
    font: "serif",
    border: "2px solid #A65C30",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/cadre-fleurs-dorees.jpg",
  },
  {
    id: "skyline_ciel",
    name: "Horizon Urbain",
    mood: "Moderne, citadin",
    background: "#EAEEF5",
    accent: "#1B58BB",
    text: "#0E1E39",
    font: "sans-serif",
    border: "2px solid #1B58BB",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/ciel-skyline.jpg",
  },
  {
    id: "cadre_navy_or",
    name: "Cadre Navy & Or",
    mood: "Sobre et corporate",
    background: "#EEEFF0",
    accent: "#305CA6",
    text: "#1A212C",
    font: "sans-serif",
    border: "2px solid #305CA6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/cadre-navy-or.jpg",
  },
  {
    id: "cadre_noir_or",
    name: "Parchemin Noir & Or",
    mood: "Cérémonie, prestige",
    background: "#F2F0ED",
    accent: "#A68230",
    text: "#322915",
    font: "serif",
    border: "2px solid #A68230",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/cadre-noir-or.jpg",
  },
  {
    id: "podium_bleu_or",
    name: "Podium Bleu & Or",
    mood: "Chic, mise en valeur",
    background: "#ECEFF2",
    accent: "#3061A6",
    text: "#122135",
    font: "sans-serif",
    border: "2px solid #3061A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/podium-bleu-or.jpg",
  },
  {
    id: "escalier_marbre",
    name: "Escalier de Marbre",
    mood: "Onirique, évasion",
    background: "#EDF0F2",
    accent: "#3085A6",
    text: "#142A33",
    font: "serif",
    border: "2px solid #3085A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/escalier-marbre.jpg",
  },
  {
    id: "allee_palmiers",
    name: "Allée de Palmiers",
    mood: "Tropical, voyage",
    background: "#EFF1ED",
    accent: "#62A630",
    text: "#213016",
    font: "sans-serif",
    border: "2px solid #62A630",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/allee-palmiers.jpg",
  },
  {
    id: "nuages_roses",
    name: "Nuages Roses & Étoiles",
    mood: "Doux, bébé fille",
    background: "#F4EBED",
    accent: "#A6304F",
    text: "#390E19",
    font: "serif",
    border: "2px solid #A6304F",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/nuages-roses-etoiles.jpg",
  },
  {
    id: "soie_bleue",
    name: "Soie Bleue Pailletée",
    mood: "Élégant, bébé garçon",
    background: "#EBF1F3",
    accent: "#307FA6",
    text: "#0E2B38",
    font: "serif",
    border: "2px solid #307FA6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/soie-bleue-paillettes.jpg",
  },
  {
    id: "givre_hiver",
    name: "Givre d'Hiver",
    mood: "Féerique, hivernal",
    background: "#EBF0F3",
    accent: "#3070A6",
    text: "#0E2539",
    font: "serif",
    border: "2px solid #3070A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/givre-hiver.jpg",
  },
  {
    id: "arabesques_emeraude",
    name: "Arabesques Émeraude",
    mood: "Raffiné, motif oriental",
    background: "#EAF4F5",
    accent: "#19B7BC",
    text: "#0E3739",
    font: "serif",
    border: "2px solid #19B7BC",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/arabesques-emeraude.jpg",
  },
  {
    id: "brume_magenta",
    name: "Brume Magenta",
    mood: "Artistique, intense",
    background: "#F2ECF1",
    accent: "#A63096",
    text: "#341230",
    font: "sans-serif",
    border: "2px solid #A63096",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/brume-magenta.jpg",
  },
  {
    id: "brume_bleu_nuit",
    name: "Brume Bleu Nuit",
    mood: "Feutré, mystérieux",
    background: "#ECF0F2",
    accent: "#3072A6",
    text: "#122534",
    font: "sans-serif",
    border: "2px solid #3072A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/brume-bleu-nuit.jpg",
  },
  {
    id: "voile_sepia",
    name: "Voile Sépia",
    mood: "Souvenir d'antan",
    background: "#F3EFEB",
    accent: "#A66530",
    text: "#38210F",
    font: "serif",
    border: "2px solid #A66530",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/voile-sepia.jpg",
  },
  {
    id: "brume_jade",
    name: "Brume Jade",
    mood: "Doux, intemporel",
    background: "#EEF1F0",
    accent: "#30A696",
    text: "#182F2C",
    font: "serif",
    border: "2px solid #30A696",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/brume-jade.jpg",
  },
  {
    id: "mandala_pastel",
    name: "Mandala Pastel",
    mood: "Bohème, spirituel",
    background: "#EDF2F1",
    accent: "#30A69F",
    text: "#143231",
    font: "serif",
    border: "2px solid #30A69F",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/mandala-pastel.jpg",
  },
  {
    id: "arabesque_verte",
    name: "Arabesque Émeraude",
    mood: "Motif géométrique oriental",
    background: "#EAF5EC",
    accent: "#09CD2D",
    text: "#0E3916",
    font: "serif",
    border: "2px solid #09CD2D",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/arabesque-verte.jpg",
  },
  {
    id: "aurore_verte",
    name: "Aurore Verte",
    mood: "Lumineux, renouveau",
    background: "#F0F3EC",
    accent: "#79A630",
    text: "#283710",
    font: "sans-serif",
    border: "2px solid #79A630",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/aurore-verte.jpg",
  },
  {
    id: "rayons_turquoise",
    name: "Rayons Turquoise",
    mood: "Éclatant, optimiste",
    background: "#EDF1EE",
    accent: "#30A64A",
    text: "#16301C",
    font: "sans-serif",
    border: "2px solid #30A64A",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/rayons-turquoise.jpg",
  },
  {
    id: "texture_turquoise",
    name: "Texture Turquoise",
    mood: "Brut, contemporain",
    background: "#EAF4F5",
    accent: "#299FAC",
    text: "#0E3439",
    font: "sans-serif",
    border: "2px solid #299FAC",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/texture-turquoise.jpg",
  },
  {
    id: "eclat_citron",
    name: "Éclat Citron Vert",
    mood: "Vitaminé, jeune",
    background: "#F0F4EA",
    accent: "#7AA62F",
    text: "#29390E",
    font: "sans-serif",
    border: "2px solid #7AA62F",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/eclat-vert-citron.jpg",
  },
  {
    id: "ruban_vert_doux",
    name: "Ruban Vert Doux",
    mood: "Frais, léger",
    background: "#EFF3EB",
    accent: "#6BA630",
    text: "#23390E",
    font: "sans-serif",
    border: "2px solid #6BA630",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/ruban-vert-doux.jpg",
  },
  {
    id: "bokeh_vert",
    name: "Bokeh Vert",
    mood: "Lumineux, doux",
    background: "#F0F5EA",
    accent: "#79AC29",
    text: "#28390E",
    font: "sans-serif",
    border: "2px solid #79AC29",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/bokeh-vert.jpg",
  },
  {
    id: "onde_lilas",
    name: "Onde Lilas",
    mood: "Futuriste, doux",
    background: "#EAEAF5",
    accent: "#2820B5",
    text: "#100E39",
    font: "sans-serif",
    border: "2px solid #2820B5",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/onde-lilas.jpg",
  },
  {
    id: "roses_bleu_glace",
    name: "Roses Bleu Glacé",
    mood: "Romantique, hivernal",
    background: "#EBF0F4",
    accent: "#3071A6",
    text: "#0E2539",
    font: "serif",
    border: "2px solid #3071A6",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/roses-bleu-glace.jpg",
  },
  {
    id: "tulipes_bleu_blanc",
    name: "Tulipes Bleu & Blanc",
    mood: "Frais, printanier",
    background: "#EAF0F5",
    accent: "#217AB4",
    text: "#0E2839",
    font: "sans-serif",
    border: "2px solid #217AB4",
    photo_radius: "8px",
    ornament: "",
    cover_image: "/book-covers/tulipes-bleu-blanc.jpg",
  },
];

export function getBookTheme(id: string | null | undefined): BookTheme | null {
  return BOOK_THEMES.find((t) => t.id === id) ?? null;
}

export interface DedicationFontOption {
  id: string;
  label: string;
  font_family: "serif" | "sans-serif";
  font_style: "normal" | "italic";
}

// Miroir de BookThemes::dedicationFonts() côté backend — restreint aux
// familles de polices que dompdf sait rendre nativement.
export const DEDICATION_FONTS: DedicationFontOption[] = [
  { id: "classic", label: "Classique", font_family: "serif", font_style: "normal" },
  { id: "elegant_italic", label: "Élégant (italique)", font_family: "serif", font_style: "italic" },
  { id: "modern", label: "Moderne", font_family: "sans-serif", font_style: "normal" },
  { id: "modern_italic", label: "Moderne (italique)", font_family: "sans-serif", font_style: "italic" },
];

export function getDedicationFont(id: string | null | undefined): DedicationFontOption {
  return DEDICATION_FONTS.find((f) => f.id === id) ?? DEDICATION_FONTS[0];
}
